version: '3.9'
services:
  db:
    image: mysql:8.0.30-debian
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=ethereum
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=root
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
